## TEST

In [1]:
print("hello, python")

hello, python


## BASIC PYTHON

In [1]:
num1 = 10
num2 = -20
print(num1,num2)


10 -20


In [2]:
num1 = 3.14
num2 = -2.718
print(num1,num2)

3.14 -2.718


In [5]:
 str1 = 'Hello'
 str2 = "Python"

 print(str1, str2)

Hello Python


In [7]:
str3 = '''This is 
a multi-line
string.'''
print(str3)

This is 
a multi-line
string.


In [8]:
text = "Python"
print(text[0])
print(text[-1])

P
n


In [9]:
text = "Python"
print(text[0:3])
print(text[::2])

Pyt
Pto


In [21]:
text = "indexing Slicing"
print(text[3])
print(text[3:6])
print(text[-7:-3])

e
exi
Slic


In [11]:
text = "Python"
print(text.upper())
print(text.lower())

PYTHON
python


In [23]:
text = "banana"
txt = "AI Compiler Engineer"
print(text.find('a'))
print(text.count('a'))
print(txt.count('e'))
print(txt.find('e'))


1
3
3
9


In [26]:
text = " Hello world    "
print(text.strip())
print(text[:6].lstrip())

Hello world
Hello


In [16]:
text = "Python is fun"
words = text.split()
print(words)
joined_text = ''.join(words)
print(joined_text)

['Python', 'is', 'fun']
Pythonisfun


In [27]:
# Formatting

name = "Alice"
age = 30
print(f"My name is {name} and I am {age} years old.")

My name is Alice and I am 30 years old.


In [30]:
print("Hello\nPython")
print("Using\tTab\texample")
print("Print \\ backslash")

Hello
Python
Using	Tab	example
Print \ backslash


In [31]:
a = True
b = False
print(a and b)
print(a or b)
print(not a)

False
True
False


In [32]:
is_authenticated = True
has_permission = False
if is_authenticated and has_permission:
    print("YES")
else:
    print("NO")

NO


In [41]:
empty_list = [] # list : 수정가능, tuple : 수정불가/immutable한 값

num = [1,2,3,4,5,7,9,11]
fruits = ["Apple", "Banana", "Cherry", "Mango"]

print(fruits[1:4])
print(fruits[0])
print(fruits[0:2])
print(type(num[7]))
print(fruits[num[2]])

['Banana', 'Cherry', 'Mango']
Apple
['Apple', 'Banana']
<class 'int'>
Mango


In [46]:
num = [2,1,4,2,5,3]

num.append(9)
print(num)

num.sort()
print(num)

num.remove(2)
print(num)

removed_items = num.pop(2)
print(num)
print(removed_items)

num.reverse()
print(num)

count = num.count(9)
print(count)

new_num = num.copy()
print(new_num)
print(num)

another_list = [10,11,12]
combined_list = num +another_list
print(combined_list)

[2, 1, 4, 2, 5, 3, 9]
[1, 2, 2, 3, 4, 5, 9]
[1, 2, 3, 4, 5, 9]
[1, 2, 4, 5, 9]
3
[9, 5, 4, 2, 1]
1
[9, 5, 4, 2, 1]
[9, 5, 4, 2, 1]
[9, 5, 4, 2, 1, 10, 11, 12]


In [48]:
empty_tuple = 0
single_ele = (5,)

colors = ("red", "yellow", "blue", "green")
print(colors[:2])

('red', 'yellow')


In [54]:
nums = (1,2,3,4,2)
print(nums.count(2))
print(nums.index(1))

point = (2,4)
print("x : ",point[0])
print("y : ",point[1])

2
0
x :  2
y :  4


In [55]:
# Dictionary
empty_tuple = {}
person = {"name" : "Moon", "age" : 26, "city" : "New York"}

print(person["name"])

print(person["age"])
person["age"] = 27
print(person["age"])

Moon
26
27


In [57]:
# get
info = {"name":"Moon","age":21}
print(info.get("name"))

print(info.keys())

print(info.values())

print(info.items())

Moon
dict_keys(['name', 'age'])
dict_values(['Moon', 21])
dict_items([('name', 'Moon'), ('age', 21)])


#### Practice

In [59]:
#Dictionary

person = {
    "name" : "Alice",
    "age" : 25, 
    "city" : "New York"
}

print(person["age"])
person["city"] = "Los Angeles"
print(person["city"])

25
Los Angeles


In [60]:
# Tuple
coordinates = (5, 10, 15, 20)
print(coordinates[0])
print(coordinates[-1])

5
20


In [61]:
# List
fruits = ["apple", "banana", "cherry", "banana"]

fruits.remove("banana")
fruits.append("orange")

print(fruits)

['apple', 'cherry', 'banana', 'orange']


In [62]:
fruit2 = ["apple", "banana", "cherry", "banana"]
fruit3 = ["apple", "banana", "cherry", "banana"]

fruit2 = list(filter(lambda x: x != "banana", fruit2))
print(fruit2)

fruit3 = [fruit for fruit in fruit3 if fruit != "banana"]
print(fruit3)

['apple', 'cherry']
['apple', 'cherry']


In [2]:
# IF
score = 85
if score > 80:
    print("Pass")
    
# IF ELSE
num = 5
if num % 2 == 0:
    print("Even")
else:
    print("Odd")
    
# IF Elif Else
score = 85
if score >= 90:
    print("A")
elif score >=80:
    print("B")
else:
    print("C")

Pass
Odd
B


In [3]:
x, y = 10, 20
if x > 5 and y < 30:
    print("GOOD")
    

GOOD


In [5]:
# for
num = [1,2,3,4,5]
for num in num:
    print(num*2)
    
#range
for i in range(1,6):
    print(f"current value : {i}")    

2
4
6
8
10
current value : 1
current value : 2
current value : 3
current value : 4
current value : 5


In [7]:
for i in range(1,4):
    for j in range(1,3):
        print(f"i {i}, j {j}")
  
# enumerate : sequence(list, tuple, string 등) 을 돌면서 인텍스와 값을 튜플형태로 반환       
items = ["A", "B", "C"]
for idx, item in enumerate(items):  
    print(f"index {idx} : {item}")

i 1, j 1
i 1, j 2
i 2, j 1
i 2, j 2
i 3, j 1
i 3, j 2
index 0 : A
index 1 : B
index 2 : C


In [4]:
u_input = input("입력하세요 : ")
print(u_input)

close


In [6]:
while True:
    user_input = input("Press (y/n) to exit : ")
    if user_input == "y":
        print("exit")
        break

exit


In [7]:
x = 5
while x > 0:
    print(x)
    x -= 1
else: 
    print("Stop")
    
 
n = 0
while n < 10:
    n += 1
    if n%2 == 0:
        continue
    print(n)
    if n == 7:
        break

5
4
3
2
1
Stop
1
3
5
7


In [2]:
def greet():
    print("HI")
    
greet()

HI


In [3]:
def add(a,b):
    return a+b

result = add(45,5)
print(result)

50


In [4]:
def greet(name="MOON"):
    print(f"Hi, {name}")
    
greet()
greet("Lee")

Hi, MOON
Hi, Lee


In [7]:
def multiply(*args):
    result = 1
    for num in args:
        result *= num
    return result

print(multiply(2,3,4))

24


In [8]:
def check_num(num):
    if num>0:
        return "Plus"
    elif num<0:
        return "Minus"
    else:
        return "ZERO"
    
print(check_num(5))
print(check_num(-3))
print(check_num(0))

Plus
Minus
ZERO


In [9]:
def login_check(username, password):
    if username == "admin" and password == "1234":
        return "Login"
    else:
        return "Fail"
    
print(login_check("admin","1234"))
print(login_check("admiin","1234"))

Login
Fail


In [10]:
def find_max(numbers):
    max = numbers[0]
    for num in numbers:
        if num > max:
            max = num
    return max

numbers = [1,3,4,7,2,5,16]
print(find_max(numbers))

16


In [13]:
def split_data(data, train_ratio = 0.8):
    split_index = int(len(data)*train_ratio)
    print(split_index)
    
    train_data = data[:split_index]
    test_data = data[split_index]
    return train_data, test_data

full_data = [1,2,3,4,5,6,7,8,9,10]
print("-----------데이터분할예제-----------")
print("Full Data : ", full_data)

train, test = split_data(full_data)
print("기본비율(80%)로 분할")
print("Train Data : ",train)
print("Test Data : ",test)

-----------데이터분할예제-----------
Full Data :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
8
기본비율(80%)로 분할
Train Data :  [1, 2, 3, 4, 5, 6, 7, 8]
Test Data :  9


### 람다함수

In [14]:
square = lambda x: x**2
print(square(5))

25


In [15]:
add = lambda a,b:a+b
print(add(3,5))

8


In [16]:
check_even = lambda x: "EVEN" if x%2 == 0 else "ODD"
print(check_even(4))

EVEN


In [17]:
nums = [1,5,2,8,1]
sorted_nums = sorted(nums, key=lambda x:x)
print(sorted_nums)

[1, 1, 2, 5, 8]


### 리스트 매서드

In [18]:
fruits = ["Mango", "Apple"]
fruits.append('Cherry')
print(fruits)

['Mango', 'Apple', 'Cherry']


In [20]:
fruits.extend(['cherry', 'strawberry'])
print(fruits)

['Mango', 'Apple', 'Cherry', 'cherry', 'strawberry', 'cherry', 'strawberry']


In [21]:
fruits.insert(1,"banana")
print(fruits)

['Mango', 'banana', 'Apple', 'Cherry', 'cherry', 'strawberry', 'cherry', 'strawberry']


In [22]:
fruits.remove('banana')
print(fruits)

last_item = fruits.pop()
print(last_item)
print(fruits)

['Mango', 'Apple', 'Cherry', 'cherry', 'strawberry', 'cherry', 'strawberry']
strawberry
['Mango', 'Apple', 'Cherry', 'cherry', 'strawberry', 'cherry']


In [23]:
numbers = [43,1,6,3,1]
numbers.sort()
print(numbers)

[1, 1, 3, 6, 43]


### 예외처리

In [26]:
try:
    num = int(input("숫자를 입력하세요 : "))
except ValueError:
    print("유효한 숫자를 입력해야합니다.")
else:
    print(f"입력한 숫자는 {num} 입니다.")

입력한 숫자는 0 입니다.


In [27]:
try:
    file = open("example.txt","r")
    content = file.read()
    print(content)
except FileNotFoundError:
    print("Can't find file")
finally:
    file.close()
    print("Find file")

Can't find file


NameError: name 'file' is not defined

### Numpy

In [33]:
import numpy as np

arr = np.array([1,2,3])
print(arr)



[1 2 3]


In [32]:
arr = np.arange(1,10,2)
print(arr)


[1 3 5 7 9]


In [34]:
arr = np.random.rand(3,3)
arr

array([[0.2284733 , 0.75755743, 0.08691768],
       [0.72752728, 0.82762952, 0.21606955],
       [0.81924423, 0.08423745, 0.86277776]])

In [35]:
arr = arr.reshape(1,9)
arr

array([[0.2284733 , 0.75755743, 0.08691768, 0.72752728, 0.82762952,
        0.21606955, 0.81924423, 0.08423745, 0.86277776]])

In [36]:
np.sum([1,2,3])

np.int64(6)

In [37]:
np.mean([1,2,3])

np.float64(2.0)

In [39]:
np.std([1,2,3])

np.float64(0.816496580927726)

### Pandas

In [5]:
import os
print(os.getcwd())
print(os.listdir())

c:\AI_project
['.git', '.venv', 'AI_project', 'AI_project-1', 'dataset', 'hello.ipynb', 'Practice_CodingTest.ipynb', 'pythonbasic.ipynb']


In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv('diabetes.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'diabetes.csv'